name: Python Cron Job (Trading Hours)

on:
  schedule:
    - cron: "*/5 4-10 * * 1-5"   # Stops at 10:55 UTC (3:55 PM PKT)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f cron_requirement.txt ]; then pip install -r cron_requirement.txt; fi

      - name: Run script
        run: python fetch_prices.py
